//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Imperium.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ImperiumParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface IImperiumListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.translationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTranslationUnit([NotNull] ImperiumParser.TranslationUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.translationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTranslationUnit([NotNull] ImperiumParser.TranslationUnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.uses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUses([NotNull] ImperiumParser.UsesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.uses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUses([NotNull] ImperiumParser.UsesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.scope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScope([NotNull] ImperiumParser.ScopeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.scope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScope([NotNull] ImperiumParser.ScopeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.scopeStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScopeStart([NotNull] ImperiumParser.ScopeStartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.scopeStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScopeStart([NotNull] ImperiumParser.ScopeStartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.scopeEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScopeEnd([NotNull] ImperiumParser.ScopeEndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.scopeEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScopeEnd([NotNull] ImperiumParser.ScopeEndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.assemblerToken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblerToken([NotNull] ImperiumParser.AssemblerTokenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.assemblerToken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblerToken([NotNull] ImperiumParser.AssemblerTokenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.traits"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTraits([NotNull] ImperiumParser.TraitsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.traits"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTraits([NotNull] ImperiumParser.TraitsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.traitsStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTraitsStart([NotNull] ImperiumParser.TraitsStartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.traitsStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTraitsStart([NotNull] ImperiumParser.TraitsStartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.traitsEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTraitsEnd([NotNull] ImperiumParser.TraitsEndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.traitsEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTraitsEnd([NotNull] ImperiumParser.TraitsEndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.declarationTraits"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationTraits([NotNull] ImperiumParser.DeclarationTraitsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.declarationTraits"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationTraits([NotNull] ImperiumParser.DeclarationTraitsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.declarationTrait"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationTrait([NotNull] ImperiumParser.DeclarationTraitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.declarationTrait"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationTrait([NotNull] ImperiumParser.DeclarationTraitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.procedureTraits"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureTraits([NotNull] ImperiumParser.ProcedureTraitsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.procedureTraits"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureTraits([NotNull] ImperiumParser.ProcedureTraitsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.procedureTraitsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureTraitsList([NotNull] ImperiumParser.ProcedureTraitsListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.procedureTraitsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureTraitsList([NotNull] ImperiumParser.ProcedureTraitsListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.procedureTrait"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureTrait([NotNull] ImperiumParser.ProcedureTraitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.procedureTrait"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureTrait([NotNull] ImperiumParser.ProcedureTraitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.procedureRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureRule([NotNull] ImperiumParser.ProcedureRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.procedureRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureRule([NotNull] ImperiumParser.ProcedureRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTarget([NotNull] ImperiumParser.TargetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTarget([NotNull] ImperiumParser.TargetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.asmBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsmBlock([NotNull] ImperiumParser.AsmBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.asmBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsmBlock([NotNull] ImperiumParser.AsmBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.asmOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsmOptions([NotNull] ImperiumParser.AsmOptionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.asmOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsmOptions([NotNull] ImperiumParser.AsmOptionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.functionRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionRule([NotNull] ImperiumParser.FunctionRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.functionRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionRule([NotNull] ImperiumParser.FunctionRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.procedureStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureStmt([NotNull] ImperiumParser.ProcedureStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.procedureStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureStmt([NotNull] ImperiumParser.ProcedureStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.functionStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionStmt([NotNull] ImperiumParser.FunctionStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.functionStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionStmt([NotNull] ImperiumParser.FunctionStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.targetSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTargetSpec([NotNull] ImperiumParser.TargetSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.targetSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTargetSpec([NotNull] ImperiumParser.TargetSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.procedureAttributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureAttributes([NotNull] ImperiumParser.ProcedureAttributesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.procedureAttributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureAttributes([NotNull] ImperiumParser.ProcedureAttributesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.functionAttributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionAttributes([NotNull] ImperiumParser.FunctionAttributesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.functionAttributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionAttributes([NotNull] ImperiumParser.FunctionAttributesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.procedureEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureEnd([NotNull] ImperiumParser.ProcedureEndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.procedureEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureEnd([NotNull] ImperiumParser.ProcedureEndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.functionEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionEnd([NotNull] ImperiumParser.FunctionEndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.functionEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionEnd([NotNull] ImperiumParser.FunctionEndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.returnsDescriptor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnsDescriptor([NotNull] ImperiumParser.ReturnsDescriptorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.returnsDescriptor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnsDescriptor([NotNull] ImperiumParser.ReturnsDescriptorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.terminator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerminator([NotNull] ImperiumParser.TerminatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.terminator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerminator([NotNull] ImperiumParser.TerminatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.labelStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabelStmt([NotNull] ImperiumParser.LabelStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.labelStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabelStmt([NotNull] ImperiumParser.LabelStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Declaration</c>
	/// labeled alternative in <see cref="ImperiumParser.passiveStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] ImperiumParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Declaration</c>
	/// labeled alternative in <see cref="ImperiumParser.passiveStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] ImperiumParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Definiion</c>
	/// labeled alternative in <see cref="ImperiumParser.passiveStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefiniion([NotNull] ImperiumParser.DefiniionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Definiion</c>
	/// labeled alternative in <see cref="ImperiumParser.passiveStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefiniion([NotNull] ImperiumParser.DefiniionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Procedure</c>
	/// labeled alternative in <see cref="ImperiumParser.passiveStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedure([NotNull] ImperiumParser.ProcedureContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Procedure</c>
	/// labeled alternative in <see cref="ImperiumParser.passiveStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedure([NotNull] ImperiumParser.ProcedureContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Function</c>
	/// labeled alternative in <see cref="ImperiumParser.passiveStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction([NotNull] ImperiumParser.FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Function</c>
	/// labeled alternative in <see cref="ImperiumParser.passiveStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction([NotNull] ImperiumParser.FunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Null</c>
	/// labeled alternative in <see cref="ImperiumParser.passiveStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNull([NotNull] ImperiumParser.NullContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Null</c>
	/// labeled alternative in <see cref="ImperiumParser.passiveStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNull([NotNull] ImperiumParser.NullContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.assemblerStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblerStmt([NotNull] ImperiumParser.AssemblerStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.assemblerStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblerStmt([NotNull] ImperiumParser.AssemblerStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.assemblerInlineComment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblerInlineComment([NotNull] ImperiumParser.AssemblerInlineCommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.assemblerInlineComment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblerInlineComment([NotNull] ImperiumParser.AssemblerInlineCommentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.activeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActiveStmt([NotNull] ImperiumParser.ActiveStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.activeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActiveStmt([NotNull] ImperiumParser.ActiveStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.nullStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNullStmt([NotNull] ImperiumParser.NullStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.nullStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNullStmt([NotNull] ImperiumParser.NullStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.assignmentStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentStmt([NotNull] ImperiumParser.AssignmentStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.assignmentStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentStmt([NotNull] ImperiumParser.AssignmentStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BasicRef</c>
	/// labeled alternative in <see cref="ImperiumParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBasicRef([NotNull] ImperiumParser.BasicRefContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BasicRef</c>
	/// labeled alternative in <see cref="ImperiumParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBasicRef([NotNull] ImperiumParser.BasicRefContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PtrRef</c>
	/// labeled alternative in <see cref="ImperiumParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPtrRef([NotNull] ImperiumParser.PtrRefContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PtrRef</c>
	/// labeled alternative in <see cref="ImperiumParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPtrRef([NotNull] ImperiumParser.PtrRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArguments([NotNull] ImperiumParser.ArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArguments([NotNull] ImperiumParser.ArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.argumentsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentsList([NotNull] ImperiumParser.ArgumentsListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.argumentsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentsList([NotNull] ImperiumParser.ArgumentsListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.basicReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBasicReference([NotNull] ImperiumParser.BasicReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.basicReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBasicReference([NotNull] ImperiumParser.BasicReferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.structureQualification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructureQualification([NotNull] ImperiumParser.StructureQualificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.structureQualification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructureQualification([NotNull] ImperiumParser.StructureQualificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.structureQualificationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructureQualificationList([NotNull] ImperiumParser.StructureQualificationListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.structureQualificationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructureQualificationList([NotNull] ImperiumParser.StructureQualificationListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.subscript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubscript([NotNull] ImperiumParser.SubscriptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.subscript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubscript([NotNull] ImperiumParser.SubscriptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.subscriptCommalist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubscriptCommalist([NotNull] ImperiumParser.SubscriptCommalistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.subscriptCommalist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubscriptCommalist([NotNull] ImperiumParser.SubscriptCommalistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.parenthesizedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenthesizedExpression([NotNull] ImperiumParser.ParenthesizedExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.parenthesizedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenthesizedExpression([NotNull] ImperiumParser.ParenthesizedExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.primitiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimitiveExpression([NotNull] ImperiumParser.PrimitiveExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.primitiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimitiveExpression([NotNull] ImperiumParser.PrimitiveExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.prefixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefixExpression([NotNull] ImperiumParser.PrefixExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.prefixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefixExpression([NotNull] ImperiumParser.PrefixExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.bitAdjustOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitAdjustOperator([NotNull] ImperiumParser.BitAdjustOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.bitAdjustOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitAdjustOperator([NotNull] ImperiumParser.BitAdjustOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.additionOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditionOperator([NotNull] ImperiumParser.AdditionOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.additionOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditionOperator([NotNull] ImperiumParser.AdditionOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.multiplyOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplyOperator([NotNull] ImperiumParser.MultiplyOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.multiplyOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplyOperator([NotNull] ImperiumParser.MultiplyOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.boolAndOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolAndOperator([NotNull] ImperiumParser.BoolAndOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.boolAndOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolAndOperator([NotNull] ImperiumParser.BoolAndOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.boolXorOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolXorOperator([NotNull] ImperiumParser.BoolXorOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.boolXorOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolXorOperator([NotNull] ImperiumParser.BoolXorOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.boolOrOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolOrOperator([NotNull] ImperiumParser.BoolOrOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.boolOrOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolOrOperator([NotNull] ImperiumParser.BoolOrOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MapExpression</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMapExpression([NotNull] ImperiumParser.MapExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MapExpression</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMapExpression([NotNull] ImperiumParser.MapExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprBoolAnd</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprBoolAnd([NotNull] ImperiumParser.ExprBoolAndContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprBoolAnd</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprBoolAnd([NotNull] ImperiumParser.ExprBoolAndContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprConcat</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprConcat([NotNull] ImperiumParser.ExprConcatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprConcat</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprConcat([NotNull] ImperiumParser.ExprConcatContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprRaise</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprRaise([NotNull] ImperiumParser.ExprRaiseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprRaise</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprRaise([NotNull] ImperiumParser.ExprRaiseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprBoolXor</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprBoolXor([NotNull] ImperiumParser.ExprBoolXorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprBoolXor</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprBoolXor([NotNull] ImperiumParser.ExprBoolXorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MapArguments</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMapArguments([NotNull] ImperiumParser.MapArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MapArguments</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMapArguments([NotNull] ImperiumParser.MapArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprLogAnd</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprLogAnd([NotNull] ImperiumParser.ExprLogAndContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprLogAnd</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprLogAnd([NotNull] ImperiumParser.ExprLogAndContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprBitAdjust</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprBitAdjust([NotNull] ImperiumParser.ExprBitAdjustContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprBitAdjust</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprBitAdjust([NotNull] ImperiumParser.ExprBitAdjustContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprAddSub</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprAddSub([NotNull] ImperiumParser.ExprAddSubContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprAddSub</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprAddSub([NotNull] ImperiumParser.ExprAddSubContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprParenthesized</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprParenthesized([NotNull] ImperiumParser.ExprParenthesizedContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprParenthesized</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprParenthesized([NotNull] ImperiumParser.ExprParenthesizedContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprMulDiv</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprMulDiv([NotNull] ImperiumParser.ExprMulDivContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprMulDiv</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprMulDiv([NotNull] ImperiumParser.ExprMulDivContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprLogOr</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprLogOr([NotNull] ImperiumParser.ExprLogOrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprLogOr</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprLogOr([NotNull] ImperiumParser.ExprLogOrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprCompare</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprCompare([NotNull] ImperiumParser.ExprCompareContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprCompare</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprCompare([NotNull] ImperiumParser.ExprCompareContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprPrefixed</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprPrefixed([NotNull] ImperiumParser.ExprPrefixedContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprPrefixed</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprPrefixed([NotNull] ImperiumParser.ExprPrefixedContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprBoolOr</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprBoolOr([NotNull] ImperiumParser.ExprBoolOrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprBoolOr</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprBoolOr([NotNull] ImperiumParser.ExprBoolOrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprPrimitive</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprPrimitive([NotNull] ImperiumParser.ExprPrimitiveContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprPrimitive</c>
	/// labeled alternative in <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprPrimitive([NotNull] ImperiumParser.ExprPrimitiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.map_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMap_set([NotNull] ImperiumParser.Map_setContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.map_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMap_set([NotNull] ImperiumParser.Map_setContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.bool_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBool_set([NotNull] ImperiumParser.Bool_setContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.bool_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBool_set([NotNull] ImperiumParser.Bool_setContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.prefixOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefixOperator([NotNull] ImperiumParser.PrefixOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.prefixOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefixOperator([NotNull] ImperiumParser.PrefixOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.comparisonOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparisonOperator([NotNull] ImperiumParser.ComparisonOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.comparisonOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparisonOperator([NotNull] ImperiumParser.ComparisonOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.shiftOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShiftOperator([NotNull] ImperiumParser.ShiftOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.shiftOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShiftOperator([NotNull] ImperiumParser.ShiftOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.callStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallStmt([NotNull] ImperiumParser.CallStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.callStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallStmt([NotNull] ImperiumParser.CallStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.gotoStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGotoStmt([NotNull] ImperiumParser.GotoStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.gotoStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGotoStmt([NotNull] ImperiumParser.GotoStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.endloopStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEndloopStmt([NotNull] ImperiumParser.EndloopStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.endloopStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEndloopStmt([NotNull] ImperiumParser.EndloopStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.reloopStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReloopStmt([NotNull] ImperiumParser.ReloopStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.reloopStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReloopStmt([NotNull] ImperiumParser.ReloopStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.declareStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclareStmt([NotNull] ImperiumParser.DeclareStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.declareStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclareStmt([NotNull] ImperiumParser.DeclareStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.declareAsBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclareAsBody([NotNull] ImperiumParser.DeclareAsBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.declareAsBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclareAsBody([NotNull] ImperiumParser.DeclareAsBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.declarationBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationBody([NotNull] ImperiumParser.DeclarationBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.declarationBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationBody([NotNull] ImperiumParser.DeclarationBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.typeInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeInfo([NotNull] ImperiumParser.TypeInfoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.typeInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeInfo([NotNull] ImperiumParser.TypeInfoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.dimensionSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDimensionSuffix([NotNull] ImperiumParser.DimensionSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.dimensionSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDimensionSuffix([NotNull] ImperiumParser.DimensionSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.boundPair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoundPair([NotNull] ImperiumParser.BoundPairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.boundPair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoundPair([NotNull] ImperiumParser.BoundPairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.boundPairCommalist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoundPairCommalist([NotNull] ImperiumParser.BoundPairCommalistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.boundPairCommalist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoundPairCommalist([NotNull] ImperiumParser.BoundPairCommalistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.lowerBound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLowerBound([NotNull] ImperiumParser.LowerBoundContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.lowerBound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLowerBound([NotNull] ImperiumParser.LowerBoundContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.upperBound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUpperBound([NotNull] ImperiumParser.UpperBoundContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.upperBound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUpperBound([NotNull] ImperiumParser.UpperBoundContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.attributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributes([NotNull] ImperiumParser.AttributesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.attributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributes([NotNull] ImperiumParser.AttributesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.memoryAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemoryAttribute([NotNull] ImperiumParser.MemoryAttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.memoryAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemoryAttribute([NotNull] ImperiumParser.MemoryAttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.dataAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataAttribute([NotNull] ImperiumParser.DataAttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.dataAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataAttribute([NotNull] ImperiumParser.DataAttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.numericScale"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumericScale([NotNull] ImperiumParser.NumericScaleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.numericScale"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumericScale([NotNull] ImperiumParser.NumericScaleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.linkageOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLinkageOption([NotNull] ImperiumParser.LinkageOptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.linkageOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLinkageOption([NotNull] ImperiumParser.LinkageOptionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.linkageSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLinkageSection([NotNull] ImperiumParser.LinkageSectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.linkageSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLinkageSection([NotNull] ImperiumParser.LinkageSectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.precision"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrecision([NotNull] ImperiumParser.PrecisionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.precision"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrecision([NotNull] ImperiumParser.PrecisionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.numberOfDigits"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumberOfDigits([NotNull] ImperiumParser.NumberOfDigitsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.numberOfDigits"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumberOfDigits([NotNull] ImperiumParser.NumberOfDigitsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.scale_factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScale_factor([NotNull] ImperiumParser.Scale_factorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.scale_factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScale_factor([NotNull] ImperiumParser.Scale_factorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.maxStringLength"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMaxStringLength([NotNull] ImperiumParser.MaxStringLengthContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.maxStringLength"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMaxStringLength([NotNull] ImperiumParser.MaxStringLengthContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.maxLength"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMaxLength([NotNull] ImperiumParser.MaxLengthContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.maxLength"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMaxLength([NotNull] ImperiumParser.MaxLengthContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.based"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBased([NotNull] ImperiumParser.BasedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.based"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBased([NotNull] ImperiumParser.BasedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.defined"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefined([NotNull] ImperiumParser.DefinedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.defined"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefined([NotNull] ImperiumParser.DefinedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.coprocedureSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCoprocedureSpecifier([NotNull] ImperiumParser.CoprocedureSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.coprocedureSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCoprocedureSpecifier([NotNull] ImperiumParser.CoprocedureSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.handlerSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHandlerSpecifier([NotNull] ImperiumParser.HandlerSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.handlerSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHandlerSpecifier([NotNull] ImperiumParser.HandlerSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.parameterNameCommalist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterNameCommalist([NotNull] ImperiumParser.ParameterNameCommalistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.parameterNameCommalist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterNameCommalist([NotNull] ImperiumParser.ParameterNameCommalistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStmt([NotNull] ImperiumParser.ReturnStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStmt([NotNull] ImperiumParser.ReturnStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.ifStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStmt([NotNull] ImperiumParser.IfStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.ifStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStmt([NotNull] ImperiumParser.IfStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.ifEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfEnd([NotNull] ImperiumParser.IfEndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.ifEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfEnd([NotNull] ImperiumParser.IfEndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.thenClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThenClause([NotNull] ImperiumParser.ThenClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.thenClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThenClause([NotNull] ImperiumParser.ThenClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.elseClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseClause([NotNull] ImperiumParser.ElseClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.elseClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseClause([NotNull] ImperiumParser.ElseClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.elifClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElifClause([NotNull] ImperiumParser.ElifClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.elifClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElifClause([NotNull] ImperiumParser.ElifClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.loopStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoopStmt([NotNull] ImperiumParser.LoopStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.loopStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoopStmt([NotNull] ImperiumParser.LoopStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.whileLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileLoop([NotNull] ImperiumParser.WhileLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.whileLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileLoop([NotNull] ImperiumParser.WhileLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.untilLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUntilLoop([NotNull] ImperiumParser.UntilLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.untilLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUntilLoop([NotNull] ImperiumParser.UntilLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.loopEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoopEnd([NotNull] ImperiumParser.LoopEndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.loopEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoopEnd([NotNull] ImperiumParser.LoopEndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.whileOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileOption([NotNull] ImperiumParser.WhileOptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.whileOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileOption([NotNull] ImperiumParser.WhileOptionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.untilOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUntilOption([NotNull] ImperiumParser.UntilOptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.untilOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUntilOption([NotNull] ImperiumParser.UntilOptionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.selectStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectStmt([NotNull] ImperiumParser.SelectStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.selectStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectStmt([NotNull] ImperiumParser.SelectStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.selectEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectEnd([NotNull] ImperiumParser.SelectEndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.selectEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectEnd([NotNull] ImperiumParser.SelectEndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.selectClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectClause([NotNull] ImperiumParser.SelectClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.selectClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectClause([NotNull] ImperiumParser.SelectClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.whenClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhenClause([NotNull] ImperiumParser.WhenClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.whenClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhenClause([NotNull] ImperiumParser.WhenClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.otherwiseClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOtherwiseClause([NotNull] ImperiumParser.OtherwiseClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.otherwiseClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOtherwiseClause([NotNull] ImperiumParser.OtherwiseClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.defineStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefineStmt([NotNull] ImperiumParser.DefineStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.defineStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefineStmt([NotNull] ImperiumParser.DefineStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.enumType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumType([NotNull] ImperiumParser.EnumTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.enumType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumType([NotNull] ImperiumParser.EnumTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.aliasType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAliasType([NotNull] ImperiumParser.AliasTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.aliasType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAliasType([NotNull] ImperiumParser.AliasTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.binaryEnum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryEnum([NotNull] ImperiumParser.BinaryEnumContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.binaryEnum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryEnum([NotNull] ImperiumParser.BinaryEnumContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.decimalEnum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecimalEnum([NotNull] ImperiumParser.DecimalEnumContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.decimalEnum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecimalEnum([NotNull] ImperiumParser.DecimalEnumContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.stringEnum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringEnum([NotNull] ImperiumParser.StringEnumContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.stringEnum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringEnum([NotNull] ImperiumParser.StringEnumContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.bitEnum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitEnum([NotNull] ImperiumParser.BitEnumContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.bitEnum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitEnum([NotNull] ImperiumParser.BitEnumContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.enumBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumBody([NotNull] ImperiumParser.EnumBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.enumBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumBody([NotNull] ImperiumParser.EnumBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.enumLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumLiteral([NotNull] ImperiumParser.EnumLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.enumLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumLiteral([NotNull] ImperiumParser.EnumLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.structType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructType([NotNull] ImperiumParser.StructTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.structType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructType([NotNull] ImperiumParser.StructTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.structBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructBody([NotNull] ImperiumParser.StructBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.structBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructBody([NotNull] ImperiumParser.StructBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.structMemberList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructMemberList([NotNull] ImperiumParser.StructMemberListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.structMemberList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructMemberList([NotNull] ImperiumParser.StructMemberListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.structSubstruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructSubstruct([NotNull] ImperiumParser.StructSubstructContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.structSubstruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructSubstruct([NotNull] ImperiumParser.StructSubstructContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.structMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructMember([NotNull] ImperiumParser.StructMemberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.structMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructMember([NotNull] ImperiumParser.StructMemberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.stringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringLiteral([NotNull] ImperiumParser.StringLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.stringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringLiteral([NotNull] ImperiumParser.StringLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.numericLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumericLiteral([NotNull] ImperiumParser.NumericLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.numericLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumericLiteral([NotNull] ImperiumParser.NumericLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.hexLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHexLiteral([NotNull] ImperiumParser.HexLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.hexLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHexLiteral([NotNull] ImperiumParser.HexLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.octalLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOctalLiteral([NotNull] ImperiumParser.OctalLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.octalLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOctalLiteral([NotNull] ImperiumParser.OctalLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.decimalLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecimalLiteral([NotNull] ImperiumParser.DecimalLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.decimalLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecimalLiteral([NotNull] ImperiumParser.DecimalLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.binaryLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryLiteral([NotNull] ImperiumParser.BinaryLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.binaryLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryLiteral([NotNull] ImperiumParser.BinaryLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] ImperiumParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] ImperiumParser.IdentifierContext context);
}
