//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Imperium.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ImperiumParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface IImperiumListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.translation_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTranslation_unit([NotNull] ImperiumParser.Translation_unitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.translation_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTranslation_unit([NotNull] ImperiumParser.Translation_unitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.procedure_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedure_stmt([NotNull] ImperiumParser.Procedure_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.procedure_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedure_stmt([NotNull] ImperiumParser.Procedure_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.stmt_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmt_block([NotNull] ImperiumParser.Stmt_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.stmt_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmt_block([NotNull] ImperiumParser.Stmt_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.terminator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerminator([NotNull] ImperiumParser.TerminatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.terminator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerminator([NotNull] ImperiumParser.TerminatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.label_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabel_stmt([NotNull] ImperiumParser.Label_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.label_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabel_stmt([NotNull] ImperiumParser.Label_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PRE</c>
	/// labeled alternative in <see cref="ImperiumParser.nonexecutable_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPRE([NotNull] ImperiumParser.PREContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PRE</c>
	/// labeled alternative in <see cref="ImperiumParser.nonexecutable_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPRE([NotNull] ImperiumParser.PREContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DCL</c>
	/// labeled alternative in <see cref="ImperiumParser.nonexecutable_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDCL([NotNull] ImperiumParser.DCLContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DCL</c>
	/// labeled alternative in <see cref="ImperiumParser.nonexecutable_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDCL([NotNull] ImperiumParser.DCLContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DEF</c>
	/// labeled alternative in <see cref="ImperiumParser.nonexecutable_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDEF([NotNull] ImperiumParser.DEFContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DEF</c>
	/// labeled alternative in <see cref="ImperiumParser.nonexecutable_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDEF([NotNull] ImperiumParser.DEFContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ASSIGN</c>
	/// labeled alternative in <see cref="ImperiumParser.executable_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterASSIGN([NotNull] ImperiumParser.ASSIGNContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ASSIGN</c>
	/// labeled alternative in <see cref="ImperiumParser.executable_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitASSIGN([NotNull] ImperiumParser.ASSIGNContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>CALL</c>
	/// labeled alternative in <see cref="ImperiumParser.executable_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCALL([NotNull] ImperiumParser.CALLContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>CALL</c>
	/// labeled alternative in <see cref="ImperiumParser.executable_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCALL([NotNull] ImperiumParser.CALLContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>GOTO</c>
	/// labeled alternative in <see cref="ImperiumParser.executable_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGOTO([NotNull] ImperiumParser.GOTOContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>GOTO</c>
	/// labeled alternative in <see cref="ImperiumParser.executable_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGOTO([NotNull] ImperiumParser.GOTOContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PROC</c>
	/// labeled alternative in <see cref="ImperiumParser.executable_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPROC([NotNull] ImperiumParser.PROCContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PROC</c>
	/// labeled alternative in <see cref="ImperiumParser.executable_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPROC([NotNull] ImperiumParser.PROCContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>RET</c>
	/// labeled alternative in <see cref="ImperiumParser.executable_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRET([NotNull] ImperiumParser.RETContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>RET</c>
	/// labeled alternative in <see cref="ImperiumParser.executable_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRET([NotNull] ImperiumParser.RETContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IF</c>
	/// labeled alternative in <see cref="ImperiumParser.executable_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIF([NotNull] ImperiumParser.IFContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IF</c>
	/// labeled alternative in <see cref="ImperiumParser.executable_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIF([NotNull] ImperiumParser.IFContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LOOP</c>
	/// labeled alternative in <see cref="ImperiumParser.executable_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLOOP([NotNull] ImperiumParser.LOOPContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LOOP</c>
	/// labeled alternative in <see cref="ImperiumParser.executable_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLOOP([NotNull] ImperiumParser.LOOPContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LEAVE</c>
	/// labeled alternative in <see cref="ImperiumParser.executable_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLEAVE([NotNull] ImperiumParser.LEAVEContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LEAVE</c>
	/// labeled alternative in <see cref="ImperiumParser.executable_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLEAVE([NotNull] ImperiumParser.LEAVEContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AGAIN</c>
	/// labeled alternative in <see cref="ImperiumParser.executable_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAGAIN([NotNull] ImperiumParser.AGAINContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AGAIN</c>
	/// labeled alternative in <see cref="ImperiumParser.executable_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAGAIN([NotNull] ImperiumParser.AGAINContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.preprocessor_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPreprocessor_stmt([NotNull] ImperiumParser.Preprocessor_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.preprocessor_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPreprocessor_stmt([NotNull] ImperiumParser.Preprocessor_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.assign_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssign_stmt([NotNull] ImperiumParser.Assign_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.assign_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssign_stmt([NotNull] ImperiumParser.Assign_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BASIC_REF</c>
	/// labeled alternative in <see cref="ImperiumParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBASIC_REF([NotNull] ImperiumParser.BASIC_REFContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BASIC_REF</c>
	/// labeled alternative in <see cref="ImperiumParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBASIC_REF([NotNull] ImperiumParser.BASIC_REFContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PTR_REF</c>
	/// labeled alternative in <see cref="ImperiumParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPTR_REF([NotNull] ImperiumParser.PTR_REFContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PTR_REF</c>
	/// labeled alternative in <see cref="ImperiumParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPTR_REF([NotNull] ImperiumParser.PTR_REFContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArguments([NotNull] ImperiumParser.ArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArguments([NotNull] ImperiumParser.ArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.arguments_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArguments_list([NotNull] ImperiumParser.Arguments_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.arguments_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArguments_list([NotNull] ImperiumParser.Arguments_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.basic_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBasic_reference([NotNull] ImperiumParser.Basic_referenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.basic_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBasic_reference([NotNull] ImperiumParser.Basic_referenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.structure_qualification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructure_qualification([NotNull] ImperiumParser.Structure_qualificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.structure_qualification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructure_qualification([NotNull] ImperiumParser.Structure_qualificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.structure_qualification_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructure_qualification_list([NotNull] ImperiumParser.Structure_qualification_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.structure_qualification_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructure_qualification_list([NotNull] ImperiumParser.Structure_qualification_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.subscript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubscript([NotNull] ImperiumParser.SubscriptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.subscript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubscript([NotNull] ImperiumParser.SubscriptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.subscript_commalist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubscript_commalist([NotNull] ImperiumParser.Subscript_commalistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.subscript_commalist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubscript_commalist([NotNull] ImperiumParser.Subscript_commalistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] ImperiumParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] ImperiumParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.expression_9"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_9([NotNull] ImperiumParser.Expression_9Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.expression_9"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_9([NotNull] ImperiumParser.Expression_9Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.expression_8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_8([NotNull] ImperiumParser.Expression_8Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.expression_8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_8([NotNull] ImperiumParser.Expression_8Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.expression_7"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_7([NotNull] ImperiumParser.Expression_7Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.expression_7"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_7([NotNull] ImperiumParser.Expression_7Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.expression_6"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_6([NotNull] ImperiumParser.Expression_6Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.expression_6"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_6([NotNull] ImperiumParser.Expression_6Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.expression_5"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_5([NotNull] ImperiumParser.Expression_5Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.expression_5"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_5([NotNull] ImperiumParser.Expression_5Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.expression_4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_4([NotNull] ImperiumParser.Expression_4Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.expression_4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_4([NotNull] ImperiumParser.Expression_4Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.expression_3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_3([NotNull] ImperiumParser.Expression_3Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.expression_3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_3([NotNull] ImperiumParser.Expression_3Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.expression_2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_2([NotNull] ImperiumParser.Expression_2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.expression_2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_2([NotNull] ImperiumParser.Expression_2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.expression_1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_1([NotNull] ImperiumParser.Expression_1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.expression_1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_1([NotNull] ImperiumParser.Expression_1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.prefix_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefix_expression([NotNull] ImperiumParser.Prefix_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.prefix_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefix_expression([NotNull] ImperiumParser.Prefix_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.parenthesized_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenthesized_expression([NotNull] ImperiumParser.Parenthesized_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.parenthesized_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenthesized_expression([NotNull] ImperiumParser.Parenthesized_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.primitive_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimitive_expression([NotNull] ImperiumParser.Primitive_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.primitive_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimitive_expression([NotNull] ImperiumParser.Primitive_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.prefix_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefix_operator([NotNull] ImperiumParser.Prefix_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.prefix_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefix_operator([NotNull] ImperiumParser.Prefix_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.comparison_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison_operator([NotNull] ImperiumParser.Comparison_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.comparison_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison_operator([NotNull] ImperiumParser.Comparison_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.shift_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShift_operator([NotNull] ImperiumParser.Shift_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.shift_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShift_operator([NotNull] ImperiumParser.Shift_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>KEYWD</c>
	/// labeled alternative in <see cref="ImperiumParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKEYWD([NotNull] ImperiumParser.KEYWDContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>KEYWD</c>
	/// labeled alternative in <see cref="ImperiumParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKEYWD([NotNull] ImperiumParser.KEYWDContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>identifier_IDENTIFIER</c>
	/// labeled alternative in <see cref="ImperiumParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier_IDENTIFIER([NotNull] ImperiumParser.Identifier_IDENTIFIERContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>identifier_IDENTIFIER</c>
	/// labeled alternative in <see cref="ImperiumParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier_IDENTIFIER([NotNull] ImperiumParser.Identifier_IDENTIFIERContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyword([NotNull] ImperiumParser.KeywordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyword([NotNull] ImperiumParser.KeywordContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.call_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall_stmt([NotNull] ImperiumParser.Call_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.call_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall_stmt([NotNull] ImperiumParser.Call_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.goto_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGoto_stmt([NotNull] ImperiumParser.Goto_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.goto_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGoto_stmt([NotNull] ImperiumParser.Goto_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.end_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnd_stmt([NotNull] ImperiumParser.End_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.end_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnd_stmt([NotNull] ImperiumParser.End_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.endloop_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEndloop_stmt([NotNull] ImperiumParser.Endloop_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.endloop_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEndloop_stmt([NotNull] ImperiumParser.Endloop_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.reloop_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReloop_stmt([NotNull] ImperiumParser.Reloop_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.reloop_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReloop_stmt([NotNull] ImperiumParser.Reloop_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.declare_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclare_stmt([NotNull] ImperiumParser.Declare_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.declare_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclare_stmt([NotNull] ImperiumParser.Declare_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.type_info"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_info([NotNull] ImperiumParser.Type_infoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.type_info"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_info([NotNull] ImperiumParser.Type_infoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.dimension_suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDimension_suffix([NotNull] ImperiumParser.Dimension_suffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.dimension_suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDimension_suffix([NotNull] ImperiumParser.Dimension_suffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.bound_pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBound_pair([NotNull] ImperiumParser.Bound_pairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.bound_pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBound_pair([NotNull] ImperiumParser.Bound_pairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.bound_pair_commalist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBound_pair_commalist([NotNull] ImperiumParser.Bound_pair_commalistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.bound_pair_commalist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBound_pair_commalist([NotNull] ImperiumParser.Bound_pair_commalistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.lower_bound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLower_bound([NotNull] ImperiumParser.Lower_boundContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.lower_bound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLower_bound([NotNull] ImperiumParser.Lower_boundContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.upper_bound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUpper_bound([NotNull] ImperiumParser.Upper_boundContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.upper_bound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUpper_bound([NotNull] ImperiumParser.Upper_boundContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute([NotNull] ImperiumParser.AttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute([NotNull] ImperiumParser.AttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BIN</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBIN([NotNull] ImperiumParser.BINContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BIN</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBIN([NotNull] ImperiumParser.BINContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DEC</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDEC([NotNull] ImperiumParser.DECContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DEC</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDEC([NotNull] ImperiumParser.DECContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PTR</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPTR([NotNull] ImperiumParser.PTRContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PTR</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPTR([NotNull] ImperiumParser.PTRContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BIT</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBIT([NotNull] ImperiumParser.BITContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BIT</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBIT([NotNull] ImperiumParser.BITContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>CHAR</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCHAR([NotNull] ImperiumParser.CHARContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>CHAR</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCHAR([NotNull] ImperiumParser.CHARContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>STR</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSTR([NotNull] ImperiumParser.STRContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>STR</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSTR([NotNull] ImperiumParser.STRContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ENT</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterENT([NotNull] ImperiumParser.ENTContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ENT</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitENT([NotNull] ImperiumParser.ENTContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>FIX</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFIX([NotNull] ImperiumParser.FIXContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FIX</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFIX([NotNull] ImperiumParser.FIXContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>FLT</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFLT([NotNull] ImperiumParser.FLTContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FLT</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFLT([NotNull] ImperiumParser.FLTContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>OFF</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOFF([NotNull] ImperiumParser.OFFContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>OFF</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOFF([NotNull] ImperiumParser.OFFContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VNG</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVNG([NotNull] ImperiumParser.VNGContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VNG</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVNG([NotNull] ImperiumParser.VNGContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>COR</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCOR([NotNull] ImperiumParser.CORContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>COR</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCOR([NotNull] ImperiumParser.CORContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>COF</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCOF([NotNull] ImperiumParser.COFContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>COF</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCOF([NotNull] ImperiumParser.COFContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BLTN</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBLTN([NotNull] ImperiumParser.BLTNContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BLTN</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBLTN([NotNull] ImperiumParser.BLTNContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>INTR</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterINTR([NotNull] ImperiumParser.INTRContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>INTR</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitINTR([NotNull] ImperiumParser.INTRContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IDENT</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIDENT([NotNull] ImperiumParser.IDENTContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IDENT</c>
	/// labeled alternative in <see cref="ImperiumParser.data_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIDENT([NotNull] ImperiumParser.IDENTContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.precision"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrecision([NotNull] ImperiumParser.PrecisionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.precision"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrecision([NotNull] ImperiumParser.PrecisionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.number_of_digits"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber_of_digits([NotNull] ImperiumParser.Number_of_digitsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.number_of_digits"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber_of_digits([NotNull] ImperiumParser.Number_of_digitsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.scale_factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScale_factor([NotNull] ImperiumParser.Scale_factorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.scale_factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScale_factor([NotNull] ImperiumParser.Scale_factorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.max_length"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMax_length([NotNull] ImperiumParser.Max_lengthContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.max_length"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMax_length([NotNull] ImperiumParser.Max_lengthContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.based"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBased([NotNull] ImperiumParser.BasedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.based"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBased([NotNull] ImperiumParser.BasedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.defined"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefined([NotNull] ImperiumParser.DefinedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.defined"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefined([NotNull] ImperiumParser.DefinedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.entry_information"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEntry_information([NotNull] ImperiumParser.Entry_informationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.entry_information"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEntry_information([NotNull] ImperiumParser.Entry_informationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.coprocedure_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCoprocedure_specifier([NotNull] ImperiumParser.Coprocedure_specifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.coprocedure_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCoprocedure_specifier([NotNull] ImperiumParser.Coprocedure_specifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.parameter_name_commalist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter_name_commalist([NotNull] ImperiumParser.Parameter_name_commalistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.parameter_name_commalist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter_name_commalist([NotNull] ImperiumParser.Parameter_name_commalistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.returns_descriptor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturns_descriptor([NotNull] ImperiumParser.Returns_descriptorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.returns_descriptor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturns_descriptor([NotNull] ImperiumParser.Returns_descriptorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.return_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturn_stmt([NotNull] ImperiumParser.Return_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.return_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturn_stmt([NotNull] ImperiumParser.Return_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.if_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_stmt([NotNull] ImperiumParser.If_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.if_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_stmt([NotNull] ImperiumParser.If_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.then_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThen_clause([NotNull] ImperiumParser.Then_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.then_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThen_clause([NotNull] ImperiumParser.Then_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.else_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElse_clause([NotNull] ImperiumParser.Else_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.else_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElse_clause([NotNull] ImperiumParser.Else_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.elif_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElif_clause([NotNull] ImperiumParser.Elif_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.elif_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElif_clause([NotNull] ImperiumParser.Elif_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BASIC_LOOP</c>
	/// labeled alternative in <see cref="ImperiumParser.loop_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBASIC_LOOP([NotNull] ImperiumParser.BASIC_LOOPContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BASIC_LOOP</c>
	/// labeled alternative in <see cref="ImperiumParser.loop_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBASIC_LOOP([NotNull] ImperiumParser.BASIC_LOOPContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>WHILE_UNTIL</c>
	/// labeled alternative in <see cref="ImperiumParser.loop_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWHILE_UNTIL([NotNull] ImperiumParser.WHILE_UNTILContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>WHILE_UNTIL</c>
	/// labeled alternative in <see cref="ImperiumParser.loop_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWHILE_UNTIL([NotNull] ImperiumParser.WHILE_UNTILContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UNTIL_WHILE</c>
	/// labeled alternative in <see cref="ImperiumParser.loop_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUNTIL_WHILE([NotNull] ImperiumParser.UNTIL_WHILEContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UNTIL_WHILE</c>
	/// labeled alternative in <see cref="ImperiumParser.loop_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUNTIL_WHILE([NotNull] ImperiumParser.UNTIL_WHILEContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.while_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhile_option([NotNull] ImperiumParser.While_optionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.while_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhile_option([NotNull] ImperiumParser.While_optionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.until_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUntil_option([NotNull] ImperiumParser.Until_optionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.until_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUntil_option([NotNull] ImperiumParser.Until_optionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.define_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefine_stmt([NotNull] ImperiumParser.Define_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.define_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefine_stmt([NotNull] ImperiumParser.Define_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.numeric_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumeric_literal([NotNull] ImperiumParser.Numeric_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.numeric_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumeric_literal([NotNull] ImperiumParser.Numeric_literalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.hexadecimal_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHexadecimal_literal([NotNull] ImperiumParser.Hexadecimal_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.hexadecimal_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHexadecimal_literal([NotNull] ImperiumParser.Hexadecimal_literalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.octal_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOctal_literal([NotNull] ImperiumParser.Octal_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.octal_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOctal_literal([NotNull] ImperiumParser.Octal_literalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.decimal_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecimal_literal([NotNull] ImperiumParser.Decimal_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.decimal_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecimal_literal([NotNull] ImperiumParser.Decimal_literalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ImperiumParser.binary_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinary_literal([NotNull] ImperiumParser.Binary_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ImperiumParser.binary_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinary_literal([NotNull] ImperiumParser.Binary_literalContext context);
}
